spring:
  datasource:
    host: localhost
    port: 5432
    database: litheum
    username: postgres
    password: postgres
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: true
  servlet:
    multipart:
      max-file-size: 250MB     # Set MAX_UPLOAD_FILE_SIZE in gulpfile.js
      max-request-size: 260MB  # max-file-size + 10
  sql:
    init:
      encoding: UTF-8
      mode: always
      continue-on-error: true
  # Static files configuration
  mvc:
    static-path-pattern: /api/geometries/**
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      static-locations[0]: file:src/main/resources/spatial/
      static-locations[1]: classpath:/spatial/
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024
  uploads: upload
  temporaryUploads: temporary
  #Default internal page size (Used for some high database usage methods)
  pageSize: 3
  port: 8080
security-properties:
logging:
  level:
    root: INFO
    es.udc.lbd.gema.lps: DEBUG
    es.udc.lbd.gema.lps.model.util.EnumConverter: ERROR
properties:
  clientURL: http://localhost:1234
  gis:
    defaultSrid: 4326
  environment: dev


geoserver:
  # GeoServer url also goes to gulp/config.js
  active: false
  url: http://localhost:9001/geoserver
  user: admin
  password: geoserver
  workspace: litheum
  datastore: litheum
